- name: updating packages before installing sonarqube
  apt:
    update_cache: yes
- name: installing sonarqube
  get_url:
    url:  " {{sonarqube }}"
    dest: "{{ installation_path }}"
- name: getname
  shell:  echo "{{sonarqube }}" | awk -F / '{print $NF}'
  register: sonar_directory
- name: displaying sonar-value
  debug:
    msg: "{{ sonar_directory.stdout }}"
- name: extracting the installed sonar
  unarchive:
     src: "{{ installation_path}}/{{ sonar_directory.stdout }}"
     dest: /opt
     remote_src: yes
  when: sonar_directory.rc == 0

- name: creating a user to start sonarqube 
  user:
   name: "{{sonar_username}}"
   state: present 
- name: Set password for SonarQube user
  shell: echo "{{ sonar_username }}:{{ sonar_password }}" | chpasswd

# - name: Get SonarQube directory name without .zip extension
#   set_fact:
#     sonar_directory_name: "{{ sonar_directory.stdout | regex_replace('\\.zip$', '') }}"
# - name: get name without zip 
#   shell: echo "{{ sonar_directory }}" | sed 's/\.zip$//'
#   register: valueofsonar

- name: adding directories 
  file:
    path: /opt/sonarqube-8.9.10.61524
    state: directory
    owner: "{{sonar_username}}"
    group: "{{sonar_username}}"
    recurse: yes
    mode: '0755'

- name: Uncomment and update username in sonar.sh
  replace:
    path: /opt/sonarqube-8.9.10.61524/bin/linux-x86-64/sonar.sh
    regexp: '#RUN_AS_USER='  # Specify the commented pattern to search for at the beginning of the line
    replace: 'RUN_AS_USER="{{sonar_username}}"'

- name: Allow SonarQube user to run specific commands without password
  lineinfile:
    path: /etc/sudoers
    line: '{{ sonar_username }} ALL=(ALL) NOPASSWD: ALL'

- name: starting sonarqube 
  shell: /opt/sonarqube-8.9.10.61524/bin/linux-x86-64/sonar.sh start  
  register: sonarstatus 

- name: sonarqube-status
  debug:
   msg: "{{sonarqube-status.stdout}}"
  when: sonarstatus.rc ==0