- name: updating packages before installing sonarqube
  apt:
    update_cache: yes
- name: installing sonarqube
  get_url:
    url:  " {{sonarqube }}"
    dest: "{{ installation_path }}"
- name: getname
  shell:  echo "{{sonarqube }}" | awk -F / '{print $NF}'
  register: sonar_directory
- name: displaying sonar-value
  debug:
    msg: "{{ sonar_directory.stdout }}"
- name: extracting the installed sonar
  unarchive:
     src: "{{ installation_path}}/{{ sonar_directory.stdout }}"
     dest: /opt
     remote_src: yes
  when: sonar_directory.rc == 0

- name: creating a user to start sonarqube 
  user:
   name: "{{sonar_username}}"
   state: present 

# - name: Get SonarQube directory name without .zip extension
#   set_fact:
#     sonar_directory_name: "{{ sonar_directory.stdout | regex_replace('\\.zip$', '') }}"
# - name: get name without zip 
#   shell: echo "{{ sonar_directory }}" | sed 's/\.zip$//'
#   register: valueofsonar

- name: adding directories 
  file:
    path: /opt/sonarqube-enterprise-8.9.10.61524
    #state: directory 
    owner: "{{sonar_username}}"
    group: "{{sonar_username}}"
    mode: '0755'