- name: installing wget and apt-transport-https and gnupg and lsb-release
  apt:
    name:
      - wget
      - apt-transport-https
      - gnupg
      - lsb-release

- name: installing public trivy public-key
  shell: wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null
 

- name: adding trivy repository
  lineinfile:
    path: /etc/apt/sources.list.d/trivy.list
    line: "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main"

- name: updating packages before installing trivy
  apt:
    update_cache: yes

- name: installing trivy
  apt:
    name: trivy
    state: present
